[project]
name = "mcp-hyperskill"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=0.4.1",
    "httpx>=0.28.1",
    "mcp>=1.6.0",
    "starlette>=0.46.1",
    "uvicorn>=0.34.0",
]
